window.products = [
  {
    id: 1,
    name: 'EVA коврики салона Premium',
    category: 'Салон и интерьер',
    subcategory: 'Коврики салона',
    price: 5400,
    deliveryCost: 900,
    weight: '2.6 кг',
    sku: 'INT-MAT-001',
    availability: 'В наличии',
    testedByUs: true,
    supplierType: 'factory',
    image: 'images/placeholder-eva.svg',
    images: ['images/placeholder-eva.svg', 'images/placeholder-console.svg', 'images/placeholder-booster.svg'],
    description: 'Комплект EVA ковриков с бортиками для салона Haval Big Dog / DaGou / Dargo.'
  },
  {
    id: 2,
    name: 'Держатель телефона на торпедо',
    category: 'Салон и интерьер',
    subcategory: 'Держатель телефона / навигации',
    price: 1800,
    deliveryCost: 700,
    weight: '0.4 кг',
    sku: 'INT-HOLD-014',
    availability: 'В наличии',
    testedByUs: true,
    supplierType: 'supplier',
    image: 'images/placeholder-console.svg',
    images: ['images/placeholder-console.svg', 'images/placeholder-eva.svg'],
    description: 'Надёжный магнитный держатель для телефона и навигации с установкой без сверления.'
  },
  {
    id: 3,
    name: 'Органайзер багажника складной',
    category: 'Багажник и хранение',
    subcategory: 'Органайзеры багажника',
    price: 2900,
    deliveryCost: 800,
    weight: '1.1 кг',
    sku: 'TRUNK-ORG-003',
    availability: 'Под заказ',
    description: 'Магнитный держатель телефона на дефлектор'
  },
  {
    id: 4,
    name: 'Защитная накладка на пороги (комплект)',
    category: 'Экстерьер и стайлинг',
    subcategory: 'Накладки на пороги',
    price: 4200,
    deliveryCost: 900,
    weight: '1.3 кг',
    sku: 'EXT-SILL-022',
    availability: 'В наличии',
    image: 'images/placeholder-console.svg',
    description: 'Металлизированные накладки на пороги, защищают ЛКП от царапин и следов обуви.'
  },
  {
    id: 5,
    name: 'Дефлекторы окон ветровики',
    category: 'Экстерьер и стайлинг',
    subcategory: 'Дефлекторы окон',
    price: 3600,
    deliveryCost: 800,
    weight: '1.0 кг',
    sku: 'EXT-DEF-018',
    availability: 'Под заказ',
    description: 'Гибкая LED-подсветка салона с USB'
  },
  {
    id: 6,
    name: 'Задние туманки с динамическими поворотниками',
    category: 'Свет и оптика',
    subcategory: 'Задние туманки с динамическими поворотниками',
    price: 11800,
    deliveryCost: 1400,
    weight: '2.2 кг',
    sku: 'LGT-FOG-041',
    availability: 'Под заказ',
    description: 'Автомобильный видеорегистратор 1080p с G-сенсором'
  },
  {
    id: 7,
    name: 'Дополнительные огни на решётку',
    category: 'Свет и оптика',
    subcategory: 'Дополнительные оранжевые огни на решётку',
    price: 5200,
    deliveryCost: 900,
    weight: '0.9 кг',
    sku: 'LGT-GRL-027',
    availability: 'В наличии',
    supplierType: 'factory',
    image: 'images/placeholder-booster.svg',
    description: 'Оранжевые маркерные огни на решётку радиатора в внедорожном стиле.'
  },
  {
    id: 8,
    name: 'Брызговики усиленные',
    category: 'Защита и внедорожный стиль',
    subcategory: 'Брызговики',
    price: 2700,
    deliveryCost: 700,
    weight: '1.2 кг',
    sku: 'PRT-MUD-009',
    availability: 'В наличии',
    image: 'images/placeholder-eva.svg',
    images: ['images/placeholder-eva.svg', 'images/placeholder-console.svg', 'images/placeholder-booster.svg'],
    description: 'Комплект передних и задних брызговиков для защиты кузова от грязи и камней.'
  },
  {
    id: 9,
    name: 'Поперечины на крышу алюминиевые',
    category: 'Багажные системы',
    subcategory: 'Поперечины',
    price: 8400,
    deliveryCost: 1200,
    weight: '3.8 кг',
    sku: 'RACK-CROSS-012',
    availability: 'Под заказ',
    description: 'Накладки на подстаканники'
  },
  {
    id: 9,
    name: 'Накладки',
    category: 'Салон и интерьер',
    subcategory: 'Накладки на элементы интерьера',
    price: 1199,
    deliveryCost: 392,
    weight: '0.7 кг',
    sku: 'TB-INT-006',
    availability: 'Под заказ',
    description: 'Накладки на подстаканники'
  },
  {
    id: 10,
    name: 'Компрессор для шин 12V',
    category: 'Полезные авто-гаджеты',
    subcategory: 'Компрессор / насос для шин',
    price: 3500,
    deliveryCost: 800,
    weight: '1.7 кг',
    sku: 'GAD-COMP-030',
    availability: 'В наличии',
    image: 'images/placeholder-booster.svg',
    images: ['images/placeholder-booster.svg', 'images/placeholder-console.svg'],
    description: 'Компактный компрессор для подкачки шин с цифровым индикатором давления.'
  },
  {
    id: 11,
    name: 'OBD-сканер Bluetooth',
    category: 'Полезные авто-гаджеты',
    subcategory: 'OBD-сканер',
    price: 2200,
    deliveryCost: 700,
    weight: '0.2 кг',
    sku: 'GAD-OBD-017',
    availability: 'В наличии',
    image: 'images/placeholder-booster.svg',
    description: 'Сканер ошибок и параметров двигателя с подключением к смартфону.'
  }
];
