window.products = [
  {
    id: 1,
    name: 'EVA коврики салона Premium',
    category: 'Салон и интерьер',
    subcategory: 'Коврики салона',
    price: 5400,
    deliveryPrice: 6300,
    weight: '2.6 кг',
    sku: 'INT-MAT-001',
    availability: 'В наличии',
    image: 'images/placeholder-eva.svg',
    description: 'Комплект EVA ковриков с бортиками для салона Haval Dargo / Big Dog 1 поколения.'
  },
  {
    id: 2,
    name: 'Держатель телефона на торпедо',
    category: 'Салон и интерьер',
    subcategory: 'Держатель телефона / навигации',
    price: 1800,
    deliveryPrice: 2500,
    weight: '0.4 кг',
    sku: 'INT-HOLD-014',
    availability: 'В наличии',
    image: 'images/placeholder-console.svg',
    description: 'Надёжный магнитный держатель для телефона и навигации с установкой без сверления.'
  },
  {
    id: 3,
    name: 'Органайзер багажника складной',
    category: 'Багажник и хранение',
    subcategory: 'Органайзеры багажника',
    price: 2900,
    deliveryPrice: 3700,
    weight: '1.1 кг',
    sku: 'TRUNK-ORG-003',
    availability: 'Под заказ',
    image: 'images/placeholder-console.svg',
    description: 'Складной органайзер с усиленными стенками для аккуратного хранения вещей в багажнике.'
  },
  {
    id: 4,
    name: 'Защитная накладка на пороги (комплект)',
    category: 'Экстерьер и стайлинг',
    subcategory: 'Накладки на пороги',
    price: 4200,
    deliveryPrice: 5100,
    weight: '1.3 кг',
    sku: 'EXT-SILL-022',
    availability: 'В наличии',
    image: 'images/placeholder-console.svg',
    description: 'Металлизированные накладки на пороги, защищают ЛКП от царапин и следов обуви.'
  },
  {
    id: 5,
    name: 'Дефлекторы окон ветровики',
    category: 'Экстерьер и стайлинг',
    subcategory: 'Дефлекторы окон',
    price: 3600,
    deliveryPrice: 4400,
    weight: '1.0 кг',
    sku: 'EXT-DEF-018',
    availability: 'Под заказ',
    image: 'images/shapka_deflector_1.svg',
    description: 'Комплект дефлекторов на 4 двери для комфортного проветривания в любую погоду.'
  },
  {
    id: 6,
    name: 'Задние туманки с динамическими поворотниками',
    category: 'Свет и оптика',
    subcategory: 'Задние туманки с динамическими поворотниками',
    price: 11800,
    deliveryPrice: 13200,
    weight: '2.2 кг',
    sku: 'LGT-FOG-041',
    availability: 'Под заказ',
    image: 'images/placeholder-booster.svg',
    description: 'Комплект задней оптики с динамической индикацией поворота и улучшенной видимостью.'
  },
  {
    id: 7,
    name: 'Дополнительные огни на решётку',
    category: 'Свет и оптика',
    subcategory: 'Дополнительные оранжевые огни на решётку',
    price: 5200,
    deliveryPrice: 6100,
    weight: '0.9 кг',
    sku: 'LGT-GRL-027',
    availability: 'В наличии',
    image: 'images/placeholder-booster.svg',
    description: 'Оранжевые маркерные огни на решётку радиатора в внедорожном стиле.'
  },
  {
    id: 8,
    name: 'Брызговики усиленные',
    category: 'Защита и внедорожный стиль',
    subcategory: 'Брызговики',
    price: 2700,
    deliveryPrice: 3400,
    weight: '1.2 кг',
    sku: 'PRT-MUD-009',
    availability: 'В наличии',
    image: 'images/placeholder-eva.svg',
    description: 'Комплект передних и задних брызговиков для защиты кузова от грязи и камней.'
  },
  {
    id: 9,
    name: 'Поперечины на крышу алюминиевые',
    category: 'Багажные системы',
    subcategory: 'Поперечины',
    price: 8400,
    deliveryPrice: 9600,
    weight: '3.8 кг',
    sku: 'RACK-CROSS-012',
    availability: 'Под заказ',
    image: 'images/placeholder-console.svg',
    description: 'Алюминиевые поперечины под штатные места крепления для перевозки боксов и грузов.'
  },
  {
    id: 10,
    name: 'Компрессор для шин 12V',
    category: 'Полезные авто-гаджеты',
    subcategory: 'Компрессор / насос для шин',
    price: 3500,
    deliveryPrice: 4300,
    weight: '1.7 кг',
    sku: 'GAD-COMP-030',
    availability: 'В наличии',
    image: 'images/placeholder-booster.svg',
    description: 'Компактный компрессор для подкачки шин с цифровым индикатором давления.'
  },
  {
    id: 11,
    name: 'OBD-сканер Bluetooth',
    category: 'Полезные авто-гаджеты',
    subcategory: 'OBD-сканер',
    price: 2200,
    deliveryPrice: 2900,
    weight: '0.2 кг',
    sku: 'GAD-OBD-017',
    availability: 'В наличии',
    image: 'images/placeholder-booster.svg',
    description: 'Сканер ошибок и параметров двигателя с подключением к смартфону.'
  }
];
